# ------------------------------------------------------------------------------
# Arch Linux installation configuration
# ------------------------------------------------------------------------------

# ARCH PACKAGES TO INSTALL
ARCH_PACKAGES=()
ARCH_PACKAGES+=("base")
ARCH_PACKAGES+=("linux")
ARCH_PACKAGES+=("linux-firmware")
ARCH_PACKAGES+=("sudo")
ARCH_PACKAGES+=("networkmanager")
ARCH_PACKAGES+=("$(get_microcode)") # Adds amd-ucode or intel-ucode automatically, depending on your cpu

# DISK PARTITIONS SETUP
ARCH_DISK=""
ARCH_BOOT_SIZE=512
ARCH_SWAP_SIZE=16384

# COMPUTER NAME
ARCH_HOSTNAME="Arch-PC"

# TIMEZONE
ARCH_TIMEZONE="Europe/Zagreb"

# LOCALES TO GENERATE
ARCH_LOCALE_GENERATE=()
ARCH_LOCALE_GENERATE+=("en_US.UTF-8 UTF-8")
# ARCH_LOCALE_GENERATE+=("hr_HR.UTF-8 UTF-8")

# LOCALES TO USE
ARCH_LOCALE=()
ARCH_LOCALE+=("LANG=en_US.UTF-8")
ARCH_LOCALE+=("LC_COLLATE=C.UTF-8")
ARCH_LOCALE+=("LC_CTYPE=C.UTF-8")
# ARCH_LOCALE+=("LC_ALL=en_US.UTF-8")
# ARCH_LOCALE+=("LC_ADDRESS=en_US.UTF-8 UTF-8")
# ARCH_LOCALE+=("LC_IDENTIFICATION=en_US.UTF-8 UTF-8")
# ARCH_LOCALE+=("LC_MEASUREMENT=en_US.UTF-8 UTF-8")
# ARCH_LOCALE+=("LC_MESSAGES=en_US.UTF-8 UTF-8")
# ARCH_LOCALE+=("LC_MONETARY=en_US.UTF-8 UTF-8")
# ARCH_LOCALE+=("LC_NAME=en_US.UTF-8 UTF-8")
# ARCH_LOCALE+=("LC_NUMERIC=en_US.UTF-8 UTF-8")
# ARCH_LOCALE+=("LC_PAPER=en_US.UTF-8 UTF-8")
# ARCH_LOCALE+=("LC_TELEPHONE=en_US.UTF-8 UTF-8")
# ARCH_LOCALE+=("LC_TIME=en_US.UTF-8 UTF-8")

# KEYBOARD SETTINGS

ARCH_VCONSOLE=()
ARCH_VCONSOLE+=("KEYMAP=us")
# ARCH_VCONSOLE+=("KEYMAP_TOGGLE=")
# ARCH_VCONSOLE+=("FONT=")
# ARCH_VCONSOLE+=("FONT_MAP=")
# ARCH_VCONSOLE+=("FONT_UNIMAP=")

# ARCH SERVICES TO ENABLE
ARCH_SERVICES=()
ARCH_SERVICES+=("NetworkManager")
