#!/usr/bin/env bash
#
# Bash script that installs Arch Linux following ArchLinux Wiki Installation guide:
# https://wiki.archlinux.org/title/installation_guide
#
# GLOBAL VARIABLES USED THROUGH THE SCRIPT:
#
# ARCH_DISK
# ARCH_BOOT_SIZE
# ARCH_SWAP_SIZE
# ARCH_HOSTNAME
# ARCH_TIMEZONE
# ARCH_LOCALE_GENERATE
# ARCH_LOCALE
# ARCH_VCONSOLE
# ARCH_PACKAGES
# ARCH_SERVICES

# Generated by the script before installation:
# ARCH_BOOT_PARTITION
# ARCH_SWAP_PARTITION
# ARCH_ROOT_PARTITION

# Asked during installation process:
# ARCH_USER
# ARCH_PASSWORD
# ARCH_PASSWORD_VERIFY
# ARCH_ROOT_PASSWORD
# ARCH_ROOT_PASSWORD_VERIFY
# ------------------------------------------------------------------------------

set -e          # Exit script if one of the commands fail
set -u          # Treat unset variables as an error, and immediately exit.
set -o pipefail # Exit on errors in pipeline

#-------------------------------------------------------------------------------
# DISK PARTITIONS
#-------------------------------------------------------------------------------
ARCH_DISK=""
ARCH_BOOT_SIZE=512
ARCH_SWAP_SIZE=16384

#-------------------------------------------------------------------------------
# COMPUTER NAME
#-------------------------------------------------------------------------------
ARCH_HOSTNAME="Arch-PC"

#-------------------------------------------------------------------------------
# TIMEZONE
#-------------------------------------------------------------------------------
ARCH_TIMEZONE="Europe/Zagreb"

#-------------------------------------------------------------------------------
# LOCALES TO GENERATE
#-------------------------------------------------------------------------------
ARCH_LOCALE_GENERATE=()
ARCH_LOCALE_GENERATE+=("en_US.UTF-8 UTF-8")
ARCH_LOCALE_GENERATE+=("hr_HR.UTF-8 UTF-8")

#-------------------------------------------------------------------------------
# LOCALES TO USE - https://man.archlinux.org/man/locale.7
#-------------------------------------------------------------------------------
ARCH_LOCALE=()

ARCH_LOCALE+=("LANG=en_US.UTF-8 UTF-8")
ARCH_LOCALE+=("LANGUAGE=en_US.UTF-8 UTF-8")

ARCH_LOCALE+=("LC_CTYPE=C.UTF-8")
ARCH_LOCALE+=("LC_COLLATE=C.UTF-8")
ARCH_LOCALE+=("LC_MESSAGES=hr_HR.UTF-8 UTF-8")
ARCH_LOCALE+=("LC_MONETARY=hr_HR.UTF-8 UTF-8")
ARCH_LOCALE+=("LC_NUMERIC=hr_HR.UTF-8 UTF-8")
ARCH_LOCALE+=("LC_TIME=hr_HR.UTF-8 UTF-8")

ARCH_LOCALE+=("LC_ADDRESS=hr_HR.UTF-8 UTF-8")
ARCH_LOCALE+=("LC_IDENTIFICATION=hr_HR.UTF-8 UTF-8")
ARCH_LOCALE+=("LC_MEASUREMENT=hr_HR.UTF-8 UTF-8")
ARCH_LOCALE+=("LC_NAME=hr_HR.UTF-8 UTF-8")
ARCH_LOCALE+=("LC_PAPER=hr_HR.UTF-8 UTF-8")
ARCH_LOCALE+=("LC_TELEPHONE=hr_HR.UTF-8 UTF-8")

#-------------------------------------------------------------------------------
# KEYBOARD SETTINGS
#-------------------------------------------------------------------------------
ARCH_VCONSOLE=()
ARCH_VCONSOLE+=("KEYMAP=us")
# ARCH_VCONSOLE+=("KEYMAP_TOGGLE=")
# ARCH_VCONSOLE+=("FONT=")
# ARCH_VCONSOLE+=("FONT_MAP=")
# ARCH_VCONSOLE+=("FONT_UNIMAP=")

#-------------------------------------------------------------------------------
# ARCH SERVICES TO ENABLE AFTER INSTALL
#-------------------------------------------------------------------------------
ARCH_SERVICES=()
ARCH_SERVICES+=("sddm.service")
ARCH_SERVICES+=("NetworkManager")
ARCH_SERVICES+=("bluetooth.service")

#-------------------------------------------------------------------------------
# BASE ARCH LINUX INSTALLATION PACKAGES
#-------------------------------------------------------------------------------
ARCH_PACKAGES=()
ARCH_PACKAGES+=("base")             # Minimal package set to define a basic Arch Linux installation
ARCH_PACKAGES+=("linux")            # The Linux kernel and modules
ARCH_PACKAGES+=("linux-firmware")   # Firmware files for Linux
ARCH_PACKAGES+=("networkmanager")   # Network connection manager and user applications
ARCH_PACKAGES+=("sudo")             # Give certain users the ability to run some commands as root
ARCH_PACKAGES+=("$(get_microcode)") # Adds amd-ucode or intel-ucode automatically, depending on your cpu

#-------------------------------------------------------------------------------
# PLASMA DESKTOP PACKAGES
#-------------------------------------------------------------------------------
ARCH_PACKAGES+=("plasma-desktop") # KDE Plasma Desktop
ARCH_PACKAGES+=("plasma-nm")      # Plasma applet written in QML for managing network connections
ARCH_PACKAGES+=("kscreen")        # KDE screen management software
ARCH_PACKAGES+=("sddm")           # QML based X11 and Wayland display manager
ARCH_PACKAGES+=("sddm-kcm")       # KDE Config Module for SDDM
ARCH_PACKAGES+=("konsole")        # KDE terminal emulator
ARCH_PACKAGES+=("dolphin")        # KDE File Manager
ARCH_PACKAGES+=("ark")            # Archiving Tool
ARCH_PACKAGES+=("noto-fonts")     # Google Noto TTF fonts

#-------------------------------------------------------------------------------
# PLASMA DESKTOP UTILITIES
#-------------------------------------------------------------------------------
ARCH_PACKAGES+=("kcalc")                 # Scientific Calculator
ARCH_PACKAGES+=("ksystemlog")            # System log viewer tool
ARCH_PACKAGES+=("kwalletmanager")        # Wallet management tool
ARCH_PACKAGES+=("plasma-systemmonitor")  # An interface for monitoring system sensors, process information and other system resources
ARCH_PACKAGES+=("power-profiles-daemon") # Makes power profiles handling available over D-Bus
ARCH_PACKAGES+=("spectacle")             # KDE screenshot capture utility
#ARCH_PACKAGES+=("base-devel")           # Basic tools to build Arch Linux ARCH_PACKAGES
#ARCH_PACKAGES+=("cpupower")             # Linux kernel tool to examine and tune power saving related features of your processor
#ARCH_PACKAGES+=("discover")             # KDE and Plasma resources management GUI
#ARCH_PACKAGES+=("elisa")                # A simple music player aiming to provide a nice experience for its us
#ARCH_PACKAGES+=("kamoso")               # A webcam recorder from KDE community
#ARCH_PACKAGES+=("kcharselect")          # Character Selector
#ARCH_PACKAGES+=("kcolorchooser")        # Color Chooser
#ARCH_PACKAGES+=("kolourpaint")          # Paint Program
#ARCH_PACKAGES+=("lm_sensors")           # Collection of user space tools for general SMBus access and hardware monitoring
#ARCH_PACKAGES+=("okular")               # Document Viewer
#ARCH_PACKAGES+=("partitionmanager")     # A KDE utility that allows you to manage disks, partitions, and file systems
#ARCH_PACKAGES+=("yakuake")              # A drop-down terminal emulator based on KDE konsole technology

#-------------------------------------------------------------------------------
# OTHER UTILITIES
#-------------------------------------------------------------------------------
ARCH_PACKAGES+=("dosfstools") # DOS filesystem utilities
ARCH_PACKAGES+=("man-db")     # A utility for reading man pages
ARCH_PACKAGES+=("neovim")     # Fork of Vim aiming to improve user experience, plugins, and GUIs
ARCH_PACKAGES+=("ntfs-3g")    # NTFS filesystem driver and utilities

#-------------------------------------------------------------------------------
# AUDIO
#-------------------------------------------------------------------------------
ARCH_PACKAGES+=("pipewire")       # Low-latency audio/video router and processor
ARCH_PACKAGES+=("pipewire-alsa")  # ALSA configuration
ARCH_PACKAGES+=("pipewire-audio") # Audio support
ARCH_PACKAGES+=("pipewire-jack")  # JACK support
ARCH_PACKAGES+=("pipewire-pulse") # PulseAudio replacement
ARCH_PACKAGES+=("plasma-pa")      # Plasma applet for audio volume management using PulseAudio
ARCH_PACKAGES+=("wireplumber")    # Session / policy manager implementation

#-------------------------------------------------------------------------------
# BLUETOOTH
#-------------------------------------------------------------------------------
ARCH_PACKAGES+=("bluez")     # Daemons for the bluetooth protocol stack
ARCH_PACKAGES+=("bluez-qt")  # Qt wrapper for Bluez 5 DBus API
ARCH_PACKAGES+=("bluedevil") # Integrate the Bluetooth technology within KDE workspace and applications

#-------------------------------------------------------------------------------
# FONTS
#-------------------------------------------------------------------------------
#ARCH_PACKAGES+=("adobe-source-code-pro-fonts") # Monospaced font family for user interface and coding environments
#ARCH_PACKAGES+=("otf-font-awesome")            # Iconic font designed for Bootstrap
#ARCH_PACKAGES+=("ttf-cascadia-code")           # A monospaced font by Microsoft that includes programming ligatures
#ARCH_PACKAGES+=("ttf-fira-code")               # Monospaced font with programming ligatures
#ARCH_PACKAGES+=("ttf-jetbrains-mono")          # Typeface for developers, by JetBrains
#ARCH_PACKAGES+=("ttf-liberation")              # Font family which aims at metric compatibility with Arial, Times New Roman, and Courier New
#ARCH_PACKAGES+=("ttf-profont-nerd")            # Patched font ProFont from nerd fonts library
#ARCH_PACKAGES+=("ttf-roboto")                  # Google's signature family of fonts
#ARCH_PACKAGES+=("ttf-roboto-mono")             # A monospaced addition to the Roboto type family.
#ARCH_PACKAGES+=("ttf-ubuntu-font-family")      # Ubuntu font family

#-------------------------------------------------------------------------------
# APPLICATIONS
#-------------------------------------------------------------------------------
#ARCH_PACKAGES+=("firefox")           # Fast, Private & Safe Web Browser
#ARCH_PACKAGES+=("thunderbird")       # All-in-one voice and text chat for gamers
#ARCH_PACKAGES+=("keepassxc")         # Cross-platform community-driven port of Keepass password manager
#ARCH_PACKAGES+=("libreoffice-fresh") # LibreOffice branch which contains new features and program enhancements
#ARCH_PACKAGES+=("mpv")               # a free, open source, and cross-platform media player
#ARCH_PACKAGES+=("qbittorrent")       # An advanced BitTorrent client programmed in C++, based on Qt toolkit and libtorrent-rasterbar

# ------------------------------------------------------------------------------
# Generate variables not defined
# ------------------------------------------------------------------------------
[[ "$ARCH_DISK" = "/dev/nvm"* ]] && ARCH_BOOT_PARTITION="${ARCH_DISK}p1" || ARCH_BOOT_PARTITION="${ARCH_DISK}1"
[[ "$ARCH_DISK" = "/dev/nvm"* ]] && ARCH_SWAP_PARTITION="${ARCH_DISK}p2" || ARCH_SWAP_PARTITION="${ARCH_DISK}2"
[[ "$ARCH_DISK" = "/dev/nvm"* ]] && ARCH_ROOT_PARTITION="${ARCH_DISK}p3" || ARCH_ROOT_PARTITION="${ARCH_DISK}3"

# ------------------------------------------------------------------------------
# Ask for sensitive variables that can't be defined in ./arch-install.conf
# ------------------------------------------------------------------------------
get_user_data() {
    clear
    read -r -p 'Enter your username: ' ARCH_USER
    clear

    while true; do
        read -r -s -p 'User password: ' ARCH_PASSWORD
        echo
        read -r -s -p 'User password verify: ' ARCH_PASSWORD_VERIFY
        echo
        if [[ "$ARCH_PASSWORD" != "$ARCH_PASSWORD_VERIFY" ]]; then
            clear
            echo "Paswords don't match, try again:"
        else
            break
        fi
    done
    clear

    while true; do
        read -r -s -p 'Root password: ' ARCH_ROOT_PASSWORD
        echo
        read -r -s -p 'Root password verify: ' ARCH_ROOT_PASSWORD_VERIFY
        echo
        if [[ "$ARCH_ROOT_PASSWORD" != "$ARCH_ROOT_PASSWORD_VERIFY" ]]; then
            clear
            echo "Paswords don't match, try again:"
        else
            break
        fi
    done
    clear
}

# ------------------------------------------------------------------------------
# Helper function that detects and 'returns' CPU microcode
# ------------------------------------------------------------------------------
get_microcode() {
    if lscpu | grep -q "GenuineIntel"; then
        echo "intel-ucode"
    elif lscpu | grep -q "AuthenticAMD"; then
        echo "amd-ucode"
    else
        exit 1
    fi
}

# ------------------------------------------------------------------------------
# Unmount mounted partitions
# ------------------------------------------------------------------------------
partitions_unmount() {
    swapoff -a &>/dev/null || true
    umount -A -R /mnt &>/dev/null || true
}

# ------------------------------------------------------------------------------
# Partition hard drive
# ------------------------------------------------------------------------------
partitions_create() {
    parted -s "$ARCH_DISK" -- mklabel gpt \
        mkpart BOOT fat32 1MiB $((1 + "$ARCH_BOOT_SIZE"))MiB \
        mkpart SWAP linux-swap $((1 + "$ARCH_BOOT_SIZE"))MiB $((1 + "$ARCH_BOOT_SIZE" + "$ARCH_SWAP_SIZE"))MiB \
        mkpart ROOT ext4 $((1 + "$ARCH_BOOT_SIZE" + "$ARCH_SWAP_SIZE"))MiB 100% \
        set 1 boot on
}

# ------------------------------------------------------------------------------
# Format partitions
# ------------------------------------------------------------------------------
partitions_format() {
    mkfs.fat -F 32 -n BOOT "$ARCH_BOOT_PARTITION"
    mkswap -L SWAP "$ARCH_SWAP_PARTITION"
    mkfs.ext4 -F -L ROOT "$ARCH_ROOT_PARTITION"
}

# ------------------------------------------------------------------------------
# Mount partitions
# ------------------------------------------------------------------------------
partitions_mount() {
    mount "$ARCH_ROOT_PARTITION" /mnt
    mkdir /mnt/boot
    mount "$ARCH_BOOT_PARTITION" /mnt/boot
    swapon "$ARCH_SWAP_PARTITION"
}

# ------------------------------------------------------------------------------
# Install Arch linux
# ------------------------------------------------------------------------------
install_arch() {
    pacman-key --init
    pacman-key --populate
    pacman -Sy --noconfirm --disable-download-timeout archlinux-keyring
    pacstrap -K /mnt "${ARCH_PACKAGES[@]}" --disable-download-timeout
}

# ------------------------------------------------------------------------------
# Generate fstab file
# ------------------------------------------------------------------------------
generate_fstab() {
    genfstab -L /mnt >>/mnt/etc/fstab
}

# ------------------------------------------------------------------------------
# Set root password
# ------------------------------------------------------------------------------
set_root_password() {
    printf "%s\n%s" "${ARCH_ROOT_PASSWORD}" "${ARCH_ROOT_PASSWORD}" | arch-chroot /mnt passwd
}

# ------------------------------------------------------------------------------
# Add user
# ------------------------------------------------------------------------------
add_user() {
    arch-chroot /mnt useradd -m "$ARCH_USER"
    printf "%s\n%s" "${ARCH_PASSWORD}" "${ARCH_PASSWORD}" | arch-chroot /mnt passwd "$ARCH_USER"
}

# ------------------------------------------------------------------------------
# Add sudo user
# ------------------------------------------------------------------------------
add_sudo_user() {
    arch-chroot /mnt bash -c "echo '${ARCH_USER} ALL=(ALL:ALL) ALL' | EDITOR='tee -a' visudo"
}

# ------------------------------------------------------------------------------
# Create hostname
# ------------------------------------------------------------------------------
set_hostname() {
    echo "$ARCH_HOSTNAME" >/mnt/etc/hostname
}

# ------------------------------------------------------------------------------
# Set hosts
# ------------------------------------------------------------------------------
set_hosts() {
    {
        echo '127.0.0.1    localhost'
        echo '::1          localhost'
    } >/mnt/etc/hosts
}

# ------------------------------------------------------------------------------
# Localization
# ------------------------------------------------------------------------------
set_localization() {
    # Uncomment locales defined in ARCH_LOCALE_GENERATE
    for value in "${ARCH_LOCALE_GENERATE[@]}"; do
        sed -i "s/#${value}/${value}/g" "/mnt/etc/locale.gen"
    done

    # Generate locales
    arch-chroot /mnt locale-gen

    # Write locales from ARCH_LOCALE into /mnt/etc/locale.conf
    for value in "${ARCH_LOCALE[@]}"; do
        echo "$value"
    done >/mnt/etc/locale.conf
}

# ------------------------------------------------------------------------------
# Keyboard layout
# ------------------------------------------------------------------------------
set_keyboard_layout() {
    for value in "${ARCH_VCONSOLE[@]}"; do
        echo "$value"
    done >/mnt/etc/vconsole.conf
}

# ------------------------------------------------------------------------------
# Time zone
# ------------------------------------------------------------------------------
set_timezone() {
    arch-chroot /mnt ln -sf "/usr/share/zoneinfo/$ARCH_TIMEZONE" /etc/localtime
    arch-chroot /mnt hwclock --systohc
}

# ------------------------------------------------------------------------------
# Install and configure boot loader
# ------------------------------------------------------------------------------
install_bootloader() {
    arch-chroot /mnt bootctl --esp-path=/boot install

    {
        echo "default arch.conf"
        # echo "timeout 5"
    } >/mnt/boot/loader/loader.conf

    {
        echo "title Arch Linux"
        echo "linux /vmlinuz-linux"
        echo "initrd /$(get_microcode).img"
        echo "initrd /initramfs-linux.img"
        echo "options root=UUID=$(blkid -o value -s UUID "$ARCH_ROOT_PARTITION") rw"
    } >/mnt/boot/loader/entries/arch.conf

    {
        echo "title Arch Linux (fallback)"
        echo "linux /vmlinuz-linux"
        echo "initrd /$(get_microcode).img"
        echo "initrd /initramfs-linux-fallback.img"
        echo "options root=UUID=$(blkid -o value -s UUID "$ARCH_ROOT_PARTITION") rw"
    } >/mnt/boot/loader/entries/arch-fallback.conf
}

# ------------------------------------------------------------------------------
# Enable services defined in ARCH_SERVICES
# ------------------------------------------------------------------------------
enable_services() {
    for service in "${ARCH_SERVICES[@]}"; do
        arch-chroot /mnt systemctl enable "$service"
    done
}

# ------------------------------------------------------------------------------
# Main scripts entry point
# ------------------------------------------------------------------------------
main() {
    get_user_data
    partitions_unmount
    partitions_create
    partitions_format
    partitions_mount
    install_arch
    generate_fstab
    set_root_password
    add_user
    add_sudo_user
    set_hostname
    set_hosts
    set_localization
    set_keyboard_layout
    set_timezone
    install_bootloader
    enable_services
}

main

# Add NTP server sync
#
# Systemd-timesyncd
# timedatectl set-ntp true               | Enable NTP synchronization
# timedatectl set-timezone Europe/Zagreb | Set your timezone
# timedatectl status                     | Check time status
# timedatectl timesync-status            | Check NTP synchronization status
