bar {
  # Run external script to print into Swaybar
  status_command while ~/.config/sway/swaybar-scripts.sh ; do sleep 1; done

  font pango: Noto Sans Reguar 10
  gaps 0 0 0 0
  height 30px
  position bottom
  separator_symbol "|"
  workspace_min_width 30

  colors {
    # Background color of the bar.
    background $colorB1

    # Text color to be used for the statusline.
    statusline #ffffff

    # Text color to be used for the separator.
    separator $colorB8

    # Border, background and text color for a workspace button when the workspace has focus.
    focused_workspace $colorD5 $colorD5 $colorD1

    # Border, background and text color for a workspace button when the workspace does not have focus and is not active (visible) on any output. This will be the case for most workspaces.
    inactive_workspace $colorB1 $colorB1 #ffffff

    # Border, background and text color for a workspace button when the workspace contains a window with the urgency hint set.
    urgent_workspace $colorD2 $colorD2 #ffffff

    # Background color of the bar on the currently focused monitor output. If not used, the color will be taken from background.
    # focused_background <color>

    # Text color to be used for the statusline on the currently focused monitor output. If not used, the color will be taken from statusline.
    # focused_statusline <color>

    # Text color to be used for the separator on the currently focused monitor output. If not used, the color will be taken from separator.
    # focused_separator <color>

    # Border, background and text color for a workspace button when the workspace is active (visible) on some output, but the focus is on another one. You can only tell this apart from the focused workspace when you are using multiple monitors.
    # active_workspace $color05 $color03 $color00

    # Border, background and text color for the binding mode indicator. If not used, the colors will be taken from urgent_workspace.
    # binding_mode $color00 $color00 $color00
  }
}